root = "."
tmp_dir = "tmp"

[build]
cmd = "protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/user.proto && go build -o ./tmp/user-srv ./main.go"
bin = "./tmp/user-srv"
include_ext = ["go"]
exclude_dir = [".git", "vendor", "tmp", "proto"]
delay = 1000

[log]
time = true