services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-srv
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=database
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 5s
      retries: 5

volumes:
  postgres_data: